title: Veera Katharina Menz (she/her)
author: Veera Katharina Menz
email: Katharina.Menz@gmx.de
description: > # this means to ignore newlines until "baseurl:"
  Personal webpage of Data Analyst and Data Scientist Veera Katharina Menz

theme: minima

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
